version: '3'

services:
   tservice:
      container_name: tservice
      build: .
      ports:
         - "8080:8080"
      volumes:
         - ./configs:/configs
         - ./assets:/assets
      networks:
         app_net:
      entrypoint: ["/bin/app", "-config", "/configs/config.yml", "-assets", "/assets"]

networks:
   app_net:
      driver: bridge