version: '3'

services:
   tservice:
      container_name: tservice
      build: .
      ports:
         - "8085:8085"
      volumes:
         - ./configs:/configs         
      networks:
         app_net:
      entrypoint: ["/bin/app", "-config", "/configs/config.yml", "-responsePath", "/configs/responses", "-port", "8085"]

networks:
   app_net:
      driver: bridge