responses:
   lorem:
      path: /path/url/xxx
      definition:
         status_code: 200
         response: '{"hey": "you"}'
         headers: 
            - X-123:hhhh
            - X-222:32111
   lorem2:
      path: /xx-yyy/some
      definition:
         status_code: 404
         response: '{"resource":"not-found"}'
   lorem3:
      path: /lorem
      definition:
         status_code: 200
         response_file: lorem.json
      slowness:
         chance: 30
         duration: 5s
   lorem5:
      path: /loremerror
      definition:
         status_code: 200
         response_file: lorem.json
      error:
         chance: 10
         definition:
            status_code: 500   