name: Code Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.13', '1.14' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
         uses: golangci/golangci-lint-action@v1
         with:
            version: v1.28
      - uses: actions/checkout@v2
      - name: Run tests
         uses: actions/setup-go@v1
         with:
            go-version: ${{ matrix.go }}
      - run: make code_test
